name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  rollout:
    name: Rollout
    runs-on: ubuntu-latest
    environment: 
      name: prod-apply
      url: https://www.google.de
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
